name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run invoke lint
      # - name: Connect to PostgreSQL
      #   run: python3 builder.py
      #   env:
      #     POSTGRES_HOST: postgres
      #     POSTGRES_PORT: 5432
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
        env:
          TEST_DATABASE_URL: postgres://postgres_user:postgres_password@postgres:5432/postgres_db
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
